const translations = {
    en: {
        logoText: "مصنع روافد الصلب",
        logoTextEn: "Rawafid Alssalb Factory",
        navHome: "Home",
        navAbout: "About",
        navServices: "Services",
        navProducts: "Products",
        navContact: "Contact",
        heroBadge: "Buildings & Steel Structures",
        heroTitle: "ALSSALB",
        heroAr: "شركة روافد الصلب للمباني والإنشاءات الحديدية",
        heroTagline: "Specializing in design, fabrication, painting, delivery, and erection of steel structural works with ISO 9001:2015 certified quality.",
        ctaQuote: "Get a Quote",
        ctaServices: "Our Services",
        scrollText: "Scroll",
        aboutLabel: "Who We Are",
        aboutTitle: "Engineering Excellence in Steel",
        aboutSubtitle: "A high-tech facility integrating design, fabrication, surface treatment, and erection of various heavy steel structural works.",
        aboutP1: "RAWAFID ALSSALB is a specialized facility in the engineering, fabrication, surface treatment, and erection of various heavy steel structural works and steel products.",
        aboutP2: "Our team consists of highly qualified engineers, technicians, and skilled workers who accomplish client requirements with high-quality standards and within the stipulated time.",
        aboutP3: "The Engineering Department is supported by experienced engineers and equipped with state-of-the-art software to carry out design and shop fabrication drawings.",
        statISO: "9001:2015 Certified",
        statAWS: "D1.1 Standards",
        statSupport: "24/7 Project Support",
        statQuality: "Quality Control",
        servicesLabel: "What We Do",
        servicesTitle: "Our Services",
        servicesSubtitle: "Comprehensive steel fabrication and construction services for industrial, commercial, and infrastructure projects.",
        service1Title: "Structural Steel Works",
        service1Desc: "Complete fabrication and erection of hot rolled and pre-engineered steel structures for all types of buildings.",
        service2Title: "Bridges & Gantries",
        service2Desc: "Design and construction of steel bridges and gantry systems for industrial and infrastructure applications.",
        service3Title: "Plate Works",
        service3Desc: "Fabrication of storage tanks, silos, and other plate work products with precision engineering.",
        service4Title: "Pre-Engineered Buildings",
        service4Desc: "Custom pre-engineered metal building solutions for rapid construction and cost efficiency.",
        service5Title: "Surface Treatment",
        service5Desc: "Complete shot blasting and painting services meeting international coating standards.",
        service6Title: "Infrastructure Works",
        service6Desc: "Foundation works including soil preparation, compaction, and concrete foundation construction.",
        productsLabel: "Our Products",
        productsTitle: "Steel Solutions",
        productsSubtitle: "Wide range of steel products for various industrial and commercial applications.",
        valuesLabel: "Our Values",
        valuesTitle: "What Drives Us",
        valuesSubtitle: "Our commitment to excellence is guided by core values that define every project we undertake.",
        value1Title: "Islamic Ethics",
        value1Desc: "Business guided by integrity, fairness, and honesty in all relationships.",
        value2Title: "Quality",
        value2Desc: "Diligent work delivering the highest quality in everything we do.",
        value3Title: "Safety",
        value3Desc: "Protecting our workforce and environment is critical to our mission.",
        value4Title: "Integrity",
        value4Desc: "Embracing fairness, trust, and honesty through ethical behavior.",
        value5Title: "Collaboration",
        value5Desc: "Working together, sharing skills to unlock our team's potential.",
        value6Title: "Leadership",
        value6Desc: "Committed to continuous improvement with bold decisions.",
        equipmentLabel: "Our Capabilities",
        equipmentTitle: "Advanced Equipment",
        equipmentSubtitle: "State-of-the-art machinery for precision steel fabrication.",
        equip1Desc: "Heavy-duty cutting up to 110mm plates",
        equip2Desc: "Plasma cutting machine for precision cuts",
        equip3Desc: "Continuous drilling in X & Y directions",
        equip4Desc: "High-accuracy sheet metal rolling",
        equip5Desc: "Synchronized hydraulic bending system",
        equip6Desc: "Complete surface preparation system",
        contactTitle: "Let's Build Together",
        contactText: "Ready to start your next steel construction project? Contact us today for a consultation and quote.",
        contactLocation: "Location",
        contactLocationValue: "Industrial Area, Your City",
        contactPhone: "Phone",
        contactEmail: "Email",
        formName: "Name",
        formEmail: "Email",
        formPhone: "Phone",
        formSubject: "Subject",
        formProduct: "Product Interest",
        formMessage: "Message",
        formSubmit: "Send Message",
        footerLogo: "مصنع روافد الصلب",
        footerLogoEn: "Rawafid Alssalb Factory",
        footerCopyright: "© 2024 Rawafid Alssalb Factory. All rights reserved.",
        footerHome: "Home",
        footerAbout: "About",
        footerContact: "Contact",
        contactTitle: "Contact Us",
        contactTitle2: "Get In Touch",
        contactText: "Ready to start your next steel construction project? Contact us today for a consultation and quote.",
        sendEmail: "Send us an Email",
        callUs: "Call Us",
        visitUs: "Visit Us",
        overview: "Overview",
        otherProducts: "Other Products",
        specProduct: "Product Type",
        specCert: "Certification",
        specSoftware: "Design Software",
        specServices: "Services",
        specServicesText: "Design, Fabrication, Surface Treatment, Delivery, Installation",
        bridgesTitle: "Steel Bridges",
        bridgesTitleAr: "الجسور الفولاذية",
        bridgesTagline: "Infrastructure Solutions for industrial and commercial applications",
        bridgesSubtitle: "Infrastructure Solutions",
        bridgesDesc1: "Rawafid Alssalb Factory specializes in the design, fabrication, and installation of steel bridges for infrastructure projects.",
        bridgesDesc2: "We deliver high-quality bridge solutions that meet international standards.",
        bridgesFeat1: "Highway and railway bridges",
        bridgesFeat2: "Pedestrian footbridges",
        bridgesFeat3: "Industrial gantry systems",
        bridgesFeat4: "Load calculations and structural analysis",
        bridgesFeat5: "Complete surface treatment",
        bridgesFeat6: "Delivery and on-site installation",
        buildingsTitle: "Heavy Duty Buildings",
        buildingsTitleAr: "المباني ذات الأحمال الثقيلة",
        buildingsSubtitle: "Industrial & Commercial Structures",
        buildingsDesc: "We fabricate and erect heavy-duty steel buildings for industrial facilities.",
        buildingsFeat1: "Hot rolled steel structures",
        buildingsFeat2: "Pre-engineered metal buildings",
        buildingsFeat3: "Multi-story industrial buildings",
        buildingsFeat4: "Warehouse and factory structures",
        buildingsFeat5: "Custom design solutions",
        buildingsFeat6: "Complete foundation works",
        tanksTitle: "Storage Tanks & Silos",
        tanksTitleAr: "خزانات التخزين والصوامع",
        tanksSubtitle: "Industrial Storage",
        tanksDesc: "We fabricate storage tanks and silos for liquids and bulk materials.",
        tanksFeat1: "Above-ground storage tanks",
        tanksFeat2: "Grain and cement silos",
        tanksFeat3: "Pressure vessels",
        tanksFeat4: "Fuel storage tanks",
        tanksFeat5: "Water storage tanks",
        tanksFeat6: "Custom plate works",
        turbineTitle: "Turbine Houses",
        turbineTitleAr: "غرف التوربينات",
        turbineSubtitle: "Power Generation",
        turbineDesc: "We design and fabricate turbine houses for gas and steam turbines.",
        turbineFeat1: "Turbine generator foundations",
        turbineFeat2: "Power plant buildings",
        turbineFeat3: "Equipment support structures",
        turbineFeat4: "Exhaust stack supports",
        turbineFeat5: "Control room buildings",
        turbineFeat6: "Transformer platforms",
        towersTitle: "High Tension Towers",
        towersTitleAr: "أبراج الجهد العالي",
        towersSubtitle: "Transmission Lines",
        towersDesc: "We fabricate high tension towers for electricity transmission lines.",
        towersFeat1: "Transmission line towers",
        towersFeat2: "Substation structures",
        towersFeat3: "Switchyard towers",
        towersFeat4: "Telecommunication towers",
        towersFeat5: "Antenna support structures",
        towersFeat6: "Distribution towers",
        hangarsTitle: "Aircraft Hangars",
        hangarsTitleAr: "صالات للطائرات",
        hangarsSubtitle: "Aviation Facilities",
        hangarsDesc: "We design and fabricate aircraft hangars for commercial and military aviation.",
        hangarsFeat1: "Aircraft maintenance hangars",
        hangarsFeat2: "Storage hangars",
        hangarsFeat3: "Hangar door systems",
        hangarsFeat4: "Runway lighting structures",
        hangarsFeat5: "Aviation support buildings",
        hangarsFeat6: "Hangar doors and mechanisms",
        cargoTitle: "Cargo Terminals",
        cargoTitleAr: "محطات الشحن",
        cargoSubtitle: "Logistics Infrastructure",
        cargoDesc: "We fabricate cargo terminal structures for airports and seaports.",
        cargoFeat1: "Cargo warehouse buildings",
        cargoFeat2: "Freight terminal structures",
        cargoFeat3: "Loading bay canopies",
        cargoFeat4: "Conveyor support structures",
        cargoFeat5: "Cold storage facilities",
        cargoFeat6: "Logistics platforms",
        pebTitle: "Pre-Engineered Buildings",
        pebTitleAr: "المباني ذات الهيكل المسبق",
        pebSubtitle: "Custom Metal Buildings",
        pebDesc: "We provide pre-engineered metal building solutions for rapid construction.",
        pebFeat1: "Warehouses",
        pebFeat2: "Factories",
        pebFeat3: "Showrooms",
        pebFeat4: "Sports facilities",
        pebFeat5: "Agricultural buildings",
        pebFeat6: "Commercial structures",
        productBridges: "Steel Bridges",
        productBridgesSub: "Infrastructure Solutions",
        productBuildings: "Heavy Duty Buildings",
        productBuildingsSub: "Industrial Structures",
        productTanks: "Storage Tanks & Silos",
        productTanksSub: "Industrial Storage",
        productTurbine: "Turbine Houses",
        productTurbineSub: "Power Generation",
        productTowers: "High Tension Towers",
        productTowersSub: "Transmission Lines",
        productHangars: "Aircraft Hangars",
        productHangarsSub: "Aviation Facilities",
        productCargo: "Cargo Terminals",
        productCargoSub: "Logistics Infrastructure",
        productPEB: "Pre-Engineered Buildings",
        productPEBSub: "Custom Metal Buildings",
        
        // Product Detail Translations
        productTitle: "Steel Bridges",
        productTitleAr: "الجسور الفولاذية",
        productTagline: "Infrastructure Bridge Solutions for Transportation Networks",
        overview: "Overview",
        productSubtitle: "Transportation Infrastructure",
        productDesc1: "Rawafid Alssalb Factory specializes in the design, fabrication, and installation of steel bridges and gantry structures for transportation infrastructure projects. Our engineering team uses state-of-the-art structural analysis software including CSI SAP2000, ETABS, and STAAD.Pro to perform load calculations, dynamic analysis, and seismic design.",
        productDesc2: "We deliver high-quality bridge solutions that meet international standards including AASHTO bridge design specifications, AWS D1.1 and D1.5 welding codes for bridge construction, and ISO 9001:2015 quality management. All bridges undergo rigorous quality control with complete material traceability, NDT inspection, and comprehensive surface treatment.",
        feat1: "Highway and railway bridge structures (spans up to 100m)",
        feat2: "Pedestrian and cycling footbridge systems",
        feat3: "Industrial overhead gantry crane structures",
        feat4: "Complete structural load calculations and seismic analysis",
        feat5: "Full surface treatment with shot blasting and protective coating",
        feat6: "Professional delivery, site assembly, and installation services",
        specProductLabel: "Product Type",
        specProduct: "Steel Bridges & Gantry Structures",
        specCertLabel: "Certification",
        specSoftwareLabel: "Design Software",
        specSoftware: "SAP2000, ETABS, STAAD.Pro, Autodesk Advance Steel",
        specServicesLabel: "Services",
        specServicesText: "Design, Fabrication, Surface Treatment, Delivery, Installation",
        otherProducts: "Other Products",
        
        // Buildings product
        buildingsTitle: "Heavy Duty Buildings",
        buildingsTitleAr: "المباني الصناعية الثقيلة",
        buildingsTagline: "Industrial & Commercial Steel Building Systems",
        buildingsOverview: "Heavy Industrial Structures",
        buildingsDesc1: "We fabricate and erect heavy-duty steel buildings for industrial facilities, manufacturing plants, warehouses, and commercial complexes requiring high load-bearing capacity.",
        buildingsDesc2: "We offer complete turnkey solutions including structural design, shop drawing preparation, precision fabrication, and on-site installation.",
        buildingsFeat1: "Hot rolled steel frame structures with heavy column sections",
        buildingsFeat2: "Multi-story industrial buildings (up to 5 floors)",
        buildingsFeat3: "Large-span warehouse structures (spans up to 50m)",
        buildingsFeat4: "Factory buildings with overhead crane support",
        buildingsFeat5: "Custom-engineered solutions for specialized industries",
        buildingsFeat6: "Complete civil works including foundation design",
        
        // Tanks product
        tanksTitle: "Storage Tanks & Silos",
        tanksTitleAr: "خزانات التخزين والصوامع",
        tanksTagline: "Industrial Storage & Containment Systems",
        tanksOverview: "Bulk Storage Facilities",
        tanksDesc1: "We fabricate precision-engineered storage tanks and silos for liquids, petroleum products, chemicals, grains, cement, and bulk materials.",
        tanksDesc2: "Our tanks are designed according to international standards including API 650, API 620, and ASME Section VIII.",
        tanksFeat1: "Above-ground storage tanks (AST) up to 10,000m³ capacity",
        tanksFeat2: "Vertical and horizontal grain and cement silos",
        tanksFeat3: "Pressure vessels designed to ASME standards",
        tanksFeat4: "Fuel and petroleum product storage tanks (API 650)",
        tanksFeat5: "Potable and industrial water storage tanks",
        tanksFeat6: "Custom plate fabrication work for specialized applications",
        
        // Turbine product
        turbineTitle: "Turbine Houses",
        turbineTitleAr: "غرف التوربينات",
        turbineTagline: "Power Generation Facilities",
        turbineOverview: "Power Generation Structures",
        turbineDesc1: "We design and fabricate turbine houses and power plant structures for gas and steam turbines.",
        turbineDesc2: "We work with leading power companies to deliver reliable structural solutions for energy projects.",
        turbineFeat1: "Turbine generator foundations and support structures",
        turbineFeat2: "Complete power plant building structures",
        turbineFeat3: "Heavy equipment support platforms",
        turbineFeat4: "Exhaust stack supports and flue gas ducts",
        turbineFeat5: "Control room and operation buildings",
        turbineFeat6: "Transformer platforms and electrical substations",
        
        // Towers product
        towersTitle: "High Tension Towers",
        towersTitleAr: "أبراج الجهد العالي",
        towersTagline: "Transmission Line Infrastructure",
        towersOverview: "Electrical Transmission Systems",
        towersDesc1: "We fabricate high tension towers and transmission line structures for electricity distribution networks.",
        towersDesc2: "All towers are hot-dip galvanized for corrosion protection and long-term performance.",
        towersFeat1: "High voltage transmission line towers (up to 500kV)",
        towersFeat2: "Electrical substation steel structures",
        towersFeat3: "Switchyard gantries and support towers",
        towersFeat4: "Telecommunication and radio towers",
        towersFeat5: "Microwave antenna support structures",
        towersFeat6: "Distribution line poles and towers",
        
        // Hangars product
        hangarsTitle: "Aircraft Hangars",
        hangarsTitleAr: "حظائر الطيرات",
        hangarsTagline: "Aviation Infrastructure Solutions",
        hangarsOverview: "Aviation Maintenance & Storage Facilities",
        hangarsDesc1: "We design and fabricate large-span aircraft hangars for commercial airlines, military aviation, and private jet facilities.",
        hangarsDesc2: "We provide complete hangar solutions including structural steel frames, heavy-duty hangar door systems, and crane support beams.",
        hangarsFeat1: "Wide-span aircraft maintenance hangars (up to 100m clear span)",
        hangarsFeat2: "Climate-controlled storage hangars",
        hangarsFeat3: "Heavy-duty bi-fold and sliding hangar door systems",
        hangarsFeat4: "Runway and taxiway lighting support structures",
        hangarsFeat5: "Aviation workshop and office buildings",
        hangarsFeat6: "Fire suppression system support structures",
        
        // Cargo product
        cargoTitle: "Cargo Terminals",
        cargoTitleAr: "محطات الشحن",
        cargoTagline: "Logistics & Freight Infrastructure",
        cargoOverview: "Freight Handling Facilities",
        cargoDesc1: "We fabricate robust cargo terminal structures for airports, seaports, dry ports, and land border crossings.",
        cargoDesc2: "We deliver complete logistics infrastructure including large-span warehouse buildings and covered freight terminals.",
        cargoFeat1: "Large-span cargo warehouse buildings (up to 50m span)",
        cargoFeat2: "Covered freight terminal structures with overhead cranes",
        cargoFeat3: "Truck loading bay canopies and dock levelers",
        cargoFeat4: "Conveyor belt support bridges and platforms",
        cargoFeat5: "Temperature-controlled cold storage facilities",
        cargoFeat6: "Multi-level logistics sorting platforms",
        
        // PEB product
        pebTitle: "Pre-Engineered Buildings",
        pebTitleAr: "المباني مسبقة الهندسة",
        pebTagline: "Rapid Construction Metal Building Systems",
        pebOverview: "Prefabricated Steel Structures",
        pebDesc1: "We provide complete pre-engineered metal building (PEB) solutions for rapid construction and cost-effective deployment.",
        pebDesc2: "Our PEB solutions are completely customizable and designed for easy assembly with bolted connections.",
        pebFeat1: "Warehouse and distribution centers (up to 60m span)",
        pebFeat2: "Manufacturing factories and production facilities",
        pebFeat3: "Automotive showrooms and retail buildings",
        pebFeat4: "Sports halls and recreation facilities",
        pebFeat5: "Agricultural storage and livestock buildings",
        pebFeat6: "Commercial offices and retail structures"
    },
    ar: {
        logoText: "مصنع روافد الصلب",
        logoTextEn: "Rawafid Alssalb Factory",
        navHome: "الرئيسية",
        navAbout: "من نحن",
        navServices: "خدماتنا",
        navProducts: "منتجاتنا",
        navContact: "اتصل بنا",
        heroBadge: "المباني والهياكل الفولاذية",
        heroTitle: "روافد الصلب",
        heroAr: "مصنع روافد الصلب للمباني والإنشاءات الحديدية",
        heroTagline: "متخصصون في التصميم والتصنيع والطلاء والتسليم وتركيب الأعمال الهيكلية الفولاذية مع شهادة الجودة ISO 9001:2015.",
        ctaQuote: "احصل على عرض سعر",
        ctaServices: "خدماتنا",
        scrollText: "مرر للأسفل",
        aboutLabel: "من نحن",
        aboutTitle: "التميز الهندسي في الصلب",
        aboutSubtitle: "منشأة عالية التقنية تجمع بين التصميم والتصنيع والمعالجة السطحية وتركيب مختلف الأعمال الهيكلية الفولاذية الثقيلة.",
        aboutP1: "مصنع روافد الصلب هو منشأة متخصصة في الهندسة والتصنيع والمعالجة السطحية وتركيب مختلف الأعمال الهيكلية الفولاذية الثقيلة.",
        aboutP2: "يتكون فريقنا من مهندسين وفنيين وعمال ماهرين مؤهلين للغاية الذين ينجزون متطلبات العملاء بمعايير عالية الجودة.",
        aboutP3: "يدعم قسم الهندسة مهندسين ذوي خبرة ومجهز بأحدث البرمجيات لتنفيذ رسومات التصميم والتصنيع.",
        statISO: "معتمد ISO 9001:2015",
        statAWS: "معيار D1.1",
        statSupport: "دعم المشاريع على مدار الساعة",
        statQuality: "مراقبة الجودة 100%",
        servicesLabel: "ما نقدمه",
        servicesTitle: "خدماتنا",
        servicesSubtitle: "خدمات شاملة لتصنيع وبناء الهياكل الفولاذية للمشاريع الصناعية والتجارية والبنية التحتية.",
        service1Title: "الأعمال الفولاذية الهيكلية",
        service1Desc: "تصنيع وتركيب كامل للهياكل الفولاذية المدرفلة على الساخن والمباني ذات الهيكل الفولاذي المسبق الهندسة.",
        service2Title: "الجسور والرافعات",
        service2Desc: "تصميم وبناء الجسور الفولاذية وأنظمة الرافعات للتطبيقات الصناعية والبنية التحتية.",
        service3Title: "أعمال الألواح",
        service3Desc: "تصنيع خزانات الصوامع وغيرها من منتجات أعمال الألواح بهندسة دقيقة.",
        service4Title: "المباني ذات الهيكل المسبق",
        service4Desc: "حلول مباني معدنية مخصصة ذات هندسة مسبقة للبناء السريع.",
        service5Title: "المعالجة السطحية",
        service5Desc: "خدمات الصقل بالرمل والطلاء الكاملة التي تلبي معايير الطلاء الدولية.",
        service6Title: "أعمال البنية التحتية",
        service6Desc: "أعمال الأساسات بما في ذلك إعداد التربة والدمك وبناء الأساسات الخرسانية.",
        productsLabel: "منتجاتنا",
        productsTitle: "الحلول الفولاذية",
        productsSubtitle: "مجموعة واسعة من المنتجات الفولاذية لمختلف التطبيقات الصناعية والتجارية.",
        valuesLabel: "قيمنا",
        valuesTitle: "ما يحركنا",
        valuesSubtitle: "التزامنا بالتميز موجه بقيم أساسية تحدد كل مشروع نقوم به.",
        value1Title: "الأخلاق الإسلامية",
        value1Desc: "أعمال موجهة بالنزاهة والعدالة والصدق في جميع العلاقات.",
        value2Title: "الجودة",
        value2Desc: "عمل دؤوب يقدم أعلى جودة في كل ما نقوم به.",
        value3Title: "السلامة",
        value3Desc: "حماية قوتنا العاملة والبيئة أمر حيوي لالتزامنا.",
        value4Title: "النزاهة",
        value4Desc: "تقديم العدالة والثقة والصدق من خلال السلوك الأخلاقي.",
        value5Title: "التعاون",
        value5Desc: "العمل معاً، مشاركة المهارات لإطلاق إمكانيات فريقنا.",
        value6Title: "القيادة",
        value6Desc: "الالتزام بالتحسين المستمر مع قرارات جريئة.",
        equipmentLabel: "قدراتنا",
        equipmentTitle: "معدات متقدمة",
        equipmentSubtitle: "آلات حديثة لتصنيع الفولاذ بدقة عالية.",
        equip1Desc: "قطع ثقيل حتى ألواح 110 ملم",
        equip2Desc: "آلة القطع بالبلازما للقطع الدقيق",
        equip3Desc: "حفر مستمر في اتجاهي X و Y",
        equip4Desc: "لف المعادن بدقة عالية",
        equip5Desc: "نظام ثني هيدروليكي متزامن",
        equip6Desc: "نظام تحضير سطحي كامل",
        contactTitle: "اتصل بنا",
        contactTitle2: "تواصل معنا",
        contactText: "مستعد لبدء مشروعك القادم؟ تواصل معنا اليوم للاستشارة والحصول على عرض أسعار.",
        sendEmail: "راسلنا عبر البريد",
        callUs: "اتصل بنا",
        visitUs: "زورنا",
        footerLogo: "مصنع روافد الصلب",
        footerLogoEn: "Rawafid Alssalb Factory",
        footerCopyright: "© 2024 مصنع روافد الصلب. جميع الحقوق محفوظة.",
        footerHome: "الرئيسية",
        footerAbout: "من نحن",
        footerContact: "اتصل بنا",
        overview: "نظرة عامة",
        otherProducts: "منتجات أخرى",
        specProductLabel: "نوع المنتج",
        specCertLabel: "الشهادة",
        specSoftwareLabel: "برامج التصميم",
        specServicesLabel: "الخدمات",
        specServicesText: "التصميم، التصنيع، المعالجة السطحية، التسليم، التركيب",
        bridgesTitle: "الجسور الفولاذية",
        bridgesTitleAr: "الجسور الفولاذية",
        bridgesTagline: "حلول البنية التحتية للتطبيقات الصناعية والتجارية",
        bridgesSubtitle: "حلول البنية التحتية",
        bridgesDesc1: "متخصصون في تصميم وتصنيع وتركيب الجسور الفولاذية لمشاريع البنية التحتية.",
        bridgesDesc2: "نقدم حلول جسور عالية الجودة تلبي المعايير الدولية.",
        bridgesFeat1: "جسور الطرق والسكك الحديدية",
        bridgesFeat2: "ممرات المشاة",
        bridgesFeat3: "أنظمة الرافعات الصناعية",
        bridgesFeat4: "حسابات الأحمال والتحليل الإنشائي",
        bridgesFeat5: "معالجة سطحية كاملة",
        bridgesFeat6: "التسليم والتركيب في الموقع",
        buildingsTitle: "المباني ذات الأحمال الثقيلة",
        buildingsTitleAr: "المباني ذات الأحمال الثقيلة",
        buildingsSubtitle: "هياكل صناعية وتجارية",
        buildingsDesc: "نصنع ونركب مباني فولاذية ذات أحمال ثقيلة للمنشآت الصناعية.",
        buildingsFeat1: "هياكل فولاذية المدرفلة على الساخن",
        buildingsFeat2: "مباني معدنية ذات هندسة مسبقة",
        buildingsFeat3: "مباني صناعية متعددة الطوابق",
        buildingsFeat4: "هياكل المستودعات والمصانع",
        buildingsFeat5: "حلول تصميم مخصصة",
        buildingsFeat6: "أعمال الأساسات الكاملة",
        tanksTitle: "خزانات التخزين والصوامع",
        tanksTitleAr: "خزانات التخزين والصوامع",
        tanksSubtitle: "التخزين الصناعي",
        tanksDesc: "نصنع خزانات التخزين والصوامع للسوائل والمواد السائبة.",
        tanksFeat1: "خزانات تخزين فوق الأرض",
        tanksFeat2: "صوامع الحبوب والأسمنت",
        tanksFeat3: "أوعية الضغط",
        tanksFeat4: "خزانات تخزين الوقود",
        tanksFeat5: "خزانات تخزين المياه",
        tanksFeat6: "أعمال ألواح مخصصة",
        turbineTitle: "غرف التوربينات",
        turbineTitleAr: "غرف التوربينات",
        turbineSubtitle: "توليد الطاقة",
        turbineDesc: "نصمم ونصنع غرف التوربينات للتوربينات الغازية والبخارية.",
        turbineFeat1: "أساسات توربينات المولدات",
        turbineFeat2: "مباني محطات الطاقة",
        turbineFeat3: "هياكل دعم المعدات",
        turbineFeat4: "دعم مداخن العادم",
        turbineFeat5: "مباني غرف التحكم",
        turbineFeat6: "منصات المحولات",
        towersTitle: "أبراج الجهد العالي",
        towersTitleAr: "أبراج الجهد العالي",
        towersSubtitle: "خطوط النقل",
        towersDesc: "نصنع أبراج الجهد العالي لخطوط نقل الكهرباء.",
        towersFeat1: "أبراج نقل الكهرباء",
        towersFeat2: "هياكل المحطات الفرعية",
        towersFeat3: "أبراج محولات التوزيع",
        towersFeat4: "أبراج الاتصالات",
        towersFeat5: "هياكل دعم الهوائيات",
        towersFeat6: "أبراج التوزيع",
        hangarsTitle: "صالات للطائرات",
        hangarsTitleAr: "صالات للطائرات",
        hangarsSubtitle: "مرافق الطيران",
        hangarsDesc: "نصمم ونصنع صالات للطائرات للطيران التجاري والعسكري.",
        hangarsFeat1: "صالات صيانة الطائرات",
        hangarsFeat2: "صالات التخزين",
        hangarsFeat3: "أنظمة أبواب الصالات",
        hangarsFeat4: "هياكل إضاءة المدرج",
        hangarsFeat5: "مباني الدعم الجوي",
        hangarsFeat6: "آليات وأبواب الصالات",
        cargoTitle: "محطات الشحن",
        cargoTitleAr: "محطات الشحن",
        cargoSubtitle: "بنية التحتية اللوجستية",
        cargoDesc: "نصنع هياكل محطات الشحن للمطارات والموانئ.",
        cargoFeat1: "مباني مستودعات الشحن",
        cargoFeat2: "هياكل محطات البضائع",
        cargoFeat3: "أغطية أرصفة التحميل",
        cargoFeat4: "هياكل دعم الناقلات",
        cargoFeat5: "مرافق التخزين البارد",
        cargoFeat6: "منصات اللوجستيات",
        pebTitle: "المباني ذات الهيكل المسبق",
        pebTitleAr: "المباني ذات الهيكل المسبق",
        pebSubtitle: "المباني المعدنية المخصصة",
        pebDesc: "نقدم حلول المباني المعدنية ذات الهندسة المسبقة للبناء السريع.",
        pebFeat1: "المستودعات",
        pebFeat2: "المصانع",
        pebFeat3: "صالات العرض",
        pebFeat4: "المرافق الرياضية",
        pebFeat5: "المباني الزراعية",
        pebFeat6: "الهياكل التجارية",
        productBridges: "الجسور الفولاذية",
        productBridgesSub: "حلول البنية التحتية",
        productBuildings: "المباني ذات الأحمال الثقيلة",
        productBuildingsSub: "الهياكل الصناعية",
        productTanks: "خزانات التخزين والصوامع",
        productTanksSub: "التخزين الصناعي",
        productTurbine: "غرف التوربينات",
        productTurbineSub: "توليد الطاقة",
        productTowers: "أبراج الجهد العالي",
        productTowersSub: "خطوط النقل",
        productHangars: "صالات للطيارات",
        productHangarsSub: "مرافق الطيران",
        productCargo: "محطات الشحن",
        productCargoSub: "بنية التحتية اللوجستية",
        productPEB: "المباني ذات الهيكل المسبق",
        productPEBSub: "المباني المعدنية المخصصة",
        
        // Product Detail Translations - ARABIC
        // Each product has its own specific keys below
        
        // Buildings product
        buildingsTitle: "المباني الصناعية الثقيلة",
        buildingsTitleAr: "Heavy Duty Buildings",
        buildingsTagline: "أنظمة المباني الفولاذية الصناعية والتجارية",
        buildingsOverview: "الهياكل الصناعية الثقيلة",
        buildingsDesc1: "نصنع ونركب مباني فولاذية ثقيلة للمنشآت الصناعية ومصانع التصنيع والمستودعات والمجمعات التجارية.",
        buildingsDesc2: "نقدم حلولاً متكاملة تشمل التصميم الإنشائي وإعداد رسومات التصنيع والتصنيع الدقيق والتركيب في الموقع.",
        buildingsFeat1: "هياكل إطارات فولاذية مدرفلة على الساخن بأقسام أعمدة ثقيلة",
        buildingsFeat2: "مباني صناعية متعددة الطوابق (حتى 5 طوابق)",
        buildingsFeat3: "هياكل مستودعات واسعة النطاق (حتى 50 متر)",
        buildingsFeat4: "مباني المصانع مع دعم رافعة علوية",
        buildingsFeat5: "حلول هندسية مخصصة للصناعات المتخصصة",
        buildingsFeat6: "أعمال مدنية كاملة بما في ذلك تصميم الأساسات",
        
        // Tanks product
        tanksTitle: "خزانات التخزين والصوامع",
        tanksTitleAr: "Storage Tanks & Silos",
        tanksTagline: "أنظمة التخزين والاحتواء الصناعية",
        tanksOverview: "مرافق التخزين السائب",
        tanksDesc1: "نصنع خزانات تخزين وصوامع مصممة بدقة للسوائل ومنتجات البترول والمواد الكيميائية والحبوب والأسمنت.",
        tanksDesc2: "تم تصميم خزاناتنا وفقًا للمعايير الدولية بما في ذلك API 650 و API 620 و ASME القسم الثامن.",
        tanksFeat1: "خزانات تخزين فوق الأرض حتى 10,000 متر مكعب",
        tanksFeat2: "صوامع عمودية وأفقية للحبوب والأسمنت",
        tanksFeat3: "أوعية ضغط مصممة وفق معايير ASME",
        tanksFeat4: "خزانات تخزين الوقود ومنتجات البترول (API 650)",
        tanksFeat5: "خزانات تخزين المياه الصالحة للشرب والصناعية",
        tanksFeat6: "أعمال تصنيع ألواح مخصصة للتطبيقات المتخصصة",
        
        // Turbine product
        turbineTitle: "غرف التوربينات",
        turbineTitleAr: "Turbine Houses",
        turbineTagline: "مرافق توليد الطاقة",
        turbineOverview: "هياكل توليد الطاقة",
        turbineDesc1: "نصمم ونصنع غرف التوربينات وهياكل محطات الطاقة للتوربينات الغازية والبخارية.",
        turbineDesc2: "نعمل مع شركات الطاقة الرائدة لتقديم حلول إنشائية موثوقة لمشاريع الطاقة.",
        turbineFeat1: "أساسات وهياكل دعم توربينات المولدات",
        turbineFeat2: "هياكل مباني محطات الطاقة الكاملة",
        turbineFeat3: "منصات دعم المعدات الثقيلة",
        turbineFeat4: "دعم مداخن العادم وقنوات غازات المداخن",
        turbineFeat5: "مباني غرف التحكم والعمليات",
        turbineFeat6: "منصات المحولات والمحطات الفرعية الكهربائية",
        
        // Towers product
        towersTitle: "أبراج الجهد العالي",
        towersTitleAr: "High Tension Towers",
        towersTagline: "البنية التحتية لخطوط النقل",
        towersOverview: "أنظمة النقل الكهربائي",
        towersDesc1: "نصنع أبراج الجهد العالي وهياكل خطوط النقل لشبكات توزيع الكهرباء.",
        towersDesc2: "يتم غمس جميع الأبراج بالحرارة للجلفنة للحماية من التآكل والأداء طويل الأمد.",
        towersFeat1: "أبراج خطوط النقل ذات الجهد العالي (حتى 500 كيلو فولت)",
        towersFeat2: "هياكل فولاذية للمحطات الفرعية الكهربائية",
        towersFeat3: "رافعات ساحات التحويل وأبراج الدعم",
        towersFeat4: "أبراج الاتصالات والراديو",
        towersFeat5: "هياكل دعم هوائيات الميكروويف",
        towersFeat6: "أعمدة وأبراج خطوط التوزيع",
        
        // Hangars product
        hangarsTitle: "حظائر الطيرات",
        hangarsTitleAr: "Aircraft Hangars",
        hangarsTagline: "حلول البنية التحتية للطيران",
        hangarsOverview: "مرافق صيانة وتخزين الطيرات",
        hangarsDesc1: "نصمم ونصنع حظائر طيرات ذات فضاءات واسعة لشركات الطيران التجارية والعسكرية.",
        hangarsDesc2: "نقدم حلولاً كاملة للحظائر تشمل هياكل فولاذية وأنظمة أبواب ثقيلة وجسور دعم الرافعات.",
        hangarsFeat1: "حظائر صيانة الطيرات ذات الفضاء الواسع (حتى 100 متر)",
        hangarsFeat2: "حظائر تخزين بمناخ محكوم",
        hangarsFeat3: "أنظمة أبواب حظائر ثقيلة منزلقة وقابلة للطي",
        hangarsFeat4: "هياكل دعم إضاءة المدرج والممرات",
        hangarsFeat5: "مباني ورش ومكاتب الطيران",
        hangarsFeat6: "هياكل دعم أنظمة مكافحة الحرائق",
        
        // Cargo product
        cargoTitle: "محطات الشحن",
        cargoTitleAr: "Cargo Terminals",
        cargoTagline: "البنية التحتية للوجستيات والشحن",
        cargoOverview: "مرافق معالجة البضائع",
        cargoDesc1: "نصنع هياكل محطات شحن قوية للمطارات والموانئ البحرية والموانئ الجافة.",
        cargoDesc2: "نقدم بنية تحتية لوجستية كاملة تشمل مباني مستودعات واسعة ومحطات شحن مغطاة.",
        cargoFeat1: "مباني مستودعات شحن واسعة (حتى 50 متر)",
        cargoFeat2: "هياكل محطات شحن مغطاة مع رافعات علوية",
        cargoFeat3: "أغطية أرصفة تحميل الشاحنات ومعدلات المستوى",
        cargoFeat4: "جسور ومنصات دعم أحزمة النقل",
        cargoFeat5: "مرافق تخزين بارد يتم التحكم في درجة حرارتها",
        cargoFeat6: "منصات فرز لوجستية متعددة المستويات",
        
        // PEB product
        pebTitle: "المباني مسبقة الهندسة",
        pebTitleAr: "Pre-Engineered Buildings",
        pebTagline: "أنظمة المباني المعدنية للبناء السريع",
        pebOverview: "الهياكل الفولاذية الجاهزة",
        pebDesc1: "نقدم حلول مباني معدنية مسبقة الهندسة كاملة للبناء السريع والنشر الفعال من حيث التكلفة.",
        pebDesc2: "حلول المباني مسبقة الهندسة لدينا قابلة للتخصيص بالكامل ومصممة للتركيب السهل.",
        pebFeat1: "المستودعات ومراكز التوزيع (حتى 60 متر)",
        pebFeat2: "مصانع التصنيع ومرافق الإنتاج",
        pebFeat3: "صالات عرض السيارات ومباني التجزئة",
        pebFeat4: "قاعات رياضية ومرافق ترفيهية",
        pebFeat5: "مباني تخزين زراعي وثروة حيوانية",
        pebFeat6: "مكاتب تجارية وهياكل تجزئة"
    }
};

let currentLang = 'en';

function setLanguage(lang) {
    currentLang = lang;
    document.documentElement.lang = lang;
    document.body.dir = lang === 'ar' ? 'rtl' : 'ltr';

    document.querySelectorAll('[data-i18n]').forEach(el => {
        const key = el.dataset.i18n;
        if (translations[lang][key]) {
            el.textContent = translations[lang][key];
        }
    });

    document.querySelectorAll('.lang-btn').forEach(btn => {
        btn.classList.toggle('active', btn.dataset.lang === lang);
    });

    localStorage.setItem('selectedLang', lang);
    
    // Dispatch custom event for product pages to listen to
    const event = new CustomEvent('languageChanged', { detail: { lang: lang } });
    window.dispatchEvent(event);
}

document.querySelectorAll('.lang-btn').forEach(btn => {
    btn.addEventListener('click', () => {
        setLanguage(btn.dataset.lang);
    });
});

const savedLang = localStorage.getItem('selectedLang');
if (savedLang) {
    setLanguage(savedLang);
}

window.addEventListener('scroll', () => {
    const navbar = document.getElementById('navbar');
    if (navbar) {
        if (window.scrollY > 50) {
            navbar.classList.add('scrolled');
        } else {
            navbar.classList.remove('scrolled');
        }
    }
});

const mobileMenu = document.querySelector('.mobile-menu');
const navLinks = document.querySelector('.nav-links');

if (mobileMenu && navLinks) {
    mobileMenu.addEventListener('click', () => {
        mobileMenu.classList.toggle('active');
        navLinks.classList.toggle('active');
    });

    document.querySelectorAll('.nav-links a').forEach(link => {
        link.addEventListener('click', () => {
            mobileMenu.classList.remove('active');
            navLinks.classList.remove('active');
        });
    });
}

// Contact form removed - using direct email/phone links instead
