const translations = {
    en: {
        logoText: "مصنع روافد الصلب",
        logoTextEn: "Rawafid Alssalb Factory",
        navHome: "Home",
        navAbout: "About",
        navServices: "Services",
        navProducts: "Products",
        navContact: "Contact",
        heroBadge: "Buildings & Steel Structures",
        heroTitle: "ALSSALB",
        heroAr: "شركة روافد الصلب للمباني والإنشاءات الحديدية",
        heroTagline: "Specializing in design, fabrication, painting, delivery, and erection of steel structural works with ISO 9001:2015 certified quality.",
        ctaQuote: "Get a Quote",
        ctaServices: "Our Services",
        scrollText: "Scroll",
        aboutLabel: "Who We Are",
        aboutTitle: "Engineering Excellence in Steel",
        aboutSubtitle: "A high-tech facility integrating design, fabrication, surface treatment, and erection of various heavy steel structural works.",
        aboutP1: "RAWAFID ALSSALB is a specialized facility in the engineering, fabrication, surface treatment, and erection of various heavy steel structural works and steel products.",
        aboutP2: "Our team consists of highly qualified engineers, technicians, and skilled workers who accomplish client requirements with high-quality standards and within the stipulated time.",
        aboutP3: "The Engineering Department is supported by experienced engineers and equipped with state-of-the-art software to carry out design and shop fabrication drawings.",
        statISO: "9001:2015 Certified",
        statAWS: "D1.1 Standards",
        statSupport: "24/7 Project Support",
        statQuality: "Quality Control",
        servicesLabel: "What We Do",
        servicesTitle: "Our Services",
        servicesSubtitle: "Comprehensive steel fabrication and construction services for industrial, commercial, and infrastructure projects.",
        service1Title: "Structural Steel Works",
        service1Desc: "Complete fabrication and erection of hot rolled and pre-engineered steel structures for all types of buildings.",
        service2Title: "Bridges & Gantries",
        service2Desc: "Design and construction of steel bridges and gantry systems for industrial and infrastructure applications.",
        service3Title: "Plate Works",
        service3Desc: "Fabrication of storage tanks, silos, and other plate work products with precision engineering.",
        service4Title: "Pre-Engineered Buildings",
        service4Desc: "Custom pre-engineered metal building solutions for rapid construction and cost efficiency.",
        service5Title: "Surface Treatment",
        service5Desc: "Complete shot blasting and painting services meeting international coating standards.",
        service6Title: "Infrastructure Works",
        service6Desc: "Foundation works including soil preparation, compaction, and concrete foundation construction.",
        productsLabel: "Our Products",
        productsTitle: "Steel Solutions",
        productsSubtitle: "Wide range of steel products for various industrial and commercial applications.",
        valuesLabel: "Our Values",
        valuesTitle: "What Drives Us",
        valuesSubtitle: "Our commitment to excellence is guided by core values that define every project we undertake.",
        value1Title: "Islamic Ethics",
        value1Desc: "Business guided by integrity, fairness, and honesty in all relationships.",
        value2Title: "Quality",
        value2Desc: "Diligent work delivering the highest quality in everything we do.",
        value3Title: "Safety",
        value3Desc: "Protecting our workforce and environment is critical to our mission.",
        value4Title: "Integrity",
        value4Desc: "Embracing fairness, trust, and honesty through ethical behavior.",
        value5Title: "Collaboration",
        value5Desc: "Working together, sharing skills to unlock our team's potential.",
        value6Title: "Leadership",
        value6Desc: "Committed to continuous improvement with bold decisions.",
        equipmentLabel: "Our Capabilities",
        equipmentTitle: "Advanced Equipment",
        equipmentSubtitle: "State-of-the-art machinery for precision steel fabrication.",
        equip1Desc: "Heavy-duty cutting up to 110mm plates",
        equip2Desc: "Plasma cutting machine for precision cuts",
        equip3Desc: "Continuous drilling in X & Y directions",
        equip4Desc: "High-accuracy sheet metal rolling",
        equip5Desc: "Synchronized hydraulic bending system",
        equip6Desc: "Complete surface preparation system",
        contactTitle: "Let's Build Together",
        contactText: "Ready to start your next steel construction project? Contact us today for a consultation and quote.",
        contactLocation: "Location",
        contactLocationValue: "Industrial Area, Your City",
        contactPhone: "Phone",
        contactEmail: "Email",
        formName: "Name",
        formEmail: "Email",
        formPhone: "Phone",
        formSubject: "Subject",
        formProduct: "Product Interest",
        formMessage: "Message",
        formSubmit: "Send Message",
        footerLogo: "مصنع روافد الصلب",
        footerLogoEn: "Rawafid Alssalb Factory",
        footerCopyright: "© 2024 Rawafid Alssalb Factory. All rights reserved.",
        footerHome: "Home",
        footerAbout: "About",
        footerContact: "Contact",
        contactTitle: "Contact Us",
        contactTitle2: "Get In Touch",
        contactText: "Ready to start your next steel construction project? Contact us today for a consultation and quote.",
        sendEmail: "Send us an Email",
        callUs: "Call Us",
        visitUs: "Visit Us",
        overview: "Overview",
        otherProducts: "Other Products",
        specProduct: "Product Type",
        specCert: "Certification",
        specSoftware: "Design Software",
        specServices: "Services",
        specServicesText: "Design, Fabrication, Surface Treatment, Delivery, Installation",
        bridgesTitle: "Steel Bridges",
        bridgesTitleAr: "الجسور الفولاذية",
        bridgesTagline: "Infrastructure Solutions for industrial and commercial applications",
        bridgesSubtitle: "Infrastructure Solutions",
        bridgesDesc1: "Rawafid Alssalb Factory specializes in the design, fabrication, and installation of steel bridges for infrastructure projects.",
        bridgesDesc2: "We deliver high-quality bridge solutions that meet international standards.",
        bridgesFeat1: "Highway and railway bridges",
        bridgesFeat2: "Pedestrian footbridges",
        bridgesFeat3: "Industrial gantry systems",
        bridgesFeat4: "Load calculations and structural analysis",
        bridgesFeat5: "Complete surface treatment",
        bridgesFeat6: "Delivery and on-site installation",
        buildingsTitle: "Heavy Duty Buildings",
        buildingsTitleAr: "المباني ذات الأحمال الثقيلة",
        buildingsSubtitle: "Industrial & Commercial Structures",
        buildingsDesc: "We fabricate and erect heavy-duty steel buildings for industrial facilities.",
        buildingsFeat1: "Hot rolled steel structures",
        buildingsFeat2: "Pre-engineered metal buildings",
        buildingsFeat3: "Multi-story industrial buildings",
        buildingsFeat4: "Warehouse and factory structures",
        buildingsFeat5: "Custom design solutions",
        buildingsFeat6: "Complete foundation works",
        buildingsOverview: "Heavy Industrial Structures",
        buildingsDesc1: "We fabricate and erect heavy-duty steel buildings for industrial facilities, manufacturing plants, warehouses, and commercial complexes requiring high load-bearing capacity.",
        buildingsDesc2: "We offer complete turnkey solutions including structural design, shop drawing preparation, precision fabrication, and on-site installation.",
        tanksTitle: "Storage Tanks & Silos",
        tanksTitleAr: "خزانات التخزين والصوامع",
        tanksSubtitle: "Industrial Storage",
        tanksDesc: "We fabricate storage tanks and silos for liquids and bulk materials.",
        tanksFeat1: "Above-ground storage tanks",
        tanksFeat2: "Grain and cement silos",
        tanksFeat3: "Pressure vessels",
        tanksFeat4: "Fuel storage tanks",
        tanksFeat5: "Water storage tanks",
        tanksFeat6: "Custom plate works",
        tanksOverview: "Bulk Storage Facilities",
        tanksDesc1: "We fabricate precision-engineered storage tanks and silos for liquids, petroleum products, chemicals, grains, cement, and bulk materials.",
        tanksDesc2: "Our tanks are designed according to international standards including API 650, API 620, and ASME Section VIII.",
        turbineTitle: "Turbine Houses",
        turbineTitleAr: "غرف التوربينات",
        turbineSubtitle: "Power Generation",
        turbineDesc: "We design and fabricate turbine houses for gas and steam turbines.",
        turbineFeat1: "Turbine generator foundations",
        turbineFeat2: "Power plant buildings",
        turbineFeat3: "Equipment support structures",
        turbineFeat4: "Exhaust stack supports",
        turbineFeat5: "Control room buildings",
        turbineFeat6: "Transformer platforms",
        turbineOverview: "Power Generation Structures",
        turbineDesc1: "We design and fabricate turbine houses and power plant structures for gas and steam turbines. Our engineering team uses advanced structural analysis software including SAP2000 and ETABS to ensure structural integrity, seismic resistance, and compliance with international power plant standards.",
        turbineDesc2: "We work with leading power companies to deliver reliable structural solutions for energy projects. Our ISO 9001:2015 certified processes ensure quality control throughout design, fabrication, surface treatment, and installation. All welding follows AWS D1.1 standards.",
        towersTitle: "High Tension Towers",
        towersTitleAr: "أبراج الجهد العالي",
        towersSubtitle: "Transmission Lines",
        towersDesc: "We fabricate high tension towers for electricity transmission lines.",
        towersFeat1: "Transmission line towers",
        towersFeat2: "Substation structures",
        towersFeat3: "Switchyard towers",
        towersFeat4: "Telecommunication towers",
        towersFeat5: "Antenna support structures",
        towersFeat6: "Distribution towers",
        hangarsTitle: "Aircraft Hangars",
        hangarsTitleAr: "صالات للطائرات",
        hangarsSubtitle: "Aviation Facilities",
        hangarsDesc: "We design and fabricate aircraft hangars for commercial and military aviation.",
        hangarsFeat1: "Aircraft maintenance hangars",
        hangarsFeat2: "Storage hangars",
        hangarsFeat3: "Hangar door systems",
        hangarsFeat4: "Runway lighting structures",
        hangarsFeat5: "Aviation support buildings",
        hangarsFeat6: "Hangar doors and mechanisms",
        cargoTitle: "Cargo Terminals",
        cargoTitleAr: "محطات الشحن",
        cargoSubtitle: "Logistics Infrastructure",
        cargoDesc: "We fabricate cargo terminal structures for airports and seaports.",
        cargoFeat1: "Cargo warehouse buildings",
        cargoFeat2: "Freight terminal structures",
        cargoFeat3: "Loading bay canopies",
        cargoFeat4: "Conveyor support structures",
        cargoFeat5: "Cold storage facilities",
        cargoFeat6: "Logistics platforms",
        pebTitle: "Pre-Engineered Buildings",
        pebTitleAr: "المباني ذات الهيكل المسبق",
        pebSubtitle: "Custom Metal Buildings",
        pebDesc: "We provide pre-engineered metal building solutions for rapid construction.",
        pebFeat1: "Warehouses",
        pebFeat2: "Factories",
        pebFeat3: "Showrooms",
        pebFeat4: "Sports facilities",
        pebFeat5: "Agricultural buildings",
        pebFeat6: "Commercial structures",
        productBridges: "Steel Bridges",
        productBridgesSub: "Infrastructure Solutions",
        productBuildings: "Heavy Duty Buildings",
        productBuildingsSub: "Industrial Structures",
        productTanks: "Storage Tanks & Silos",
        productTanksSub: "Industrial Storage",
        productTurbine: "Turbine Houses",
        productTurbineSub: "Power Generation",
        productTowers: "High Tension Towers",
        productTowersSub: "Transmission Lines",
        productHangars: "Aircraft Hangars",
        productHangarsSub: "Aviation Facilities",
        productCargo: "Cargo Terminals",
        productCargoSub: "Logistics Infrastructure",
        productPEB: "Pre-Engineered Buildings",
        productPEBSub: "Custom Metal Buildings",
        
        productTitle: "Steel Bridges",
        productTitleAr: "الجسور الفولاذية",
        productTagline: "Infrastructure Bridge Solutions for Transportation Networks",
        productSubtitle: "Transportation Infrastructure",
        productDesc1: "Rawafid Alssalb Factory specializes in the design, fabrication, and installation of steel bridges and gantry structures for transportation infrastructure projects. Our engineering team uses state-of-the-art structural analysis software including CSI SAP2000, ETABS, and STAAD.Pro to perform load calculations, dynamic analysis, and seismic design.",
        productDesc2: "We deliver high-quality bridge solutions that meet international standards including AASHTO bridge design specifications, AWS D1.1 and D1.5 welding codes for bridge construction, and ISO 9001:2015 quality management. All bridges undergo rigorous quality control with complete material traceability, NDT inspection, and comprehensive surface treatment.",
        feat1: "Highway and railway bridge structures (spans up to 100m)",
        feat2: "Pedestrian and cycling footbridge systems",
        feat3: "Industrial overhead gantry crane structures",
        feat4: "Complete structural load calculations and seismic analysis",
        feat5: "Full surface treatment with shot blasting and protective coating",
        feat6: "Professional delivery, site assembly, and installation services",
        specProduct: "Steel Bridges & Gantry Structures",
        specCert: "ISO 9001:2015, AWS D1.1/D1.5",
        specSoftware: "SAP2000, ETABS, STAAD.Pro, Autodesk Advance Steel"
    },
    ar: {
        logoText: "مصنع روافد الصلب",
        logoTextEn: "Rawafid Alssalb Factory",
        navHome: "الرئيسية",
        navAbout: "من نحن",
        navServices: "خدماتنا",
        navProducts: "منتجاتنا",
        navContact: "اتصل بنا",
        heroBadge: "المباني والهياكل الفولاذية",
        heroTitle: "روافد الصلب",
        heroAr: "مصنع روافد الصلب للمباني والإنشاءات الحديدية",
        heroTagline: "متخصصون في التصميم والتصنيع والطلاء والتسليم وتركيب الأعمال الهيكلية الفولاذية مع شهادة الجودة ISO 9001:2015.",
        ctaQuote: "احصل على عرض سعر",
        ctaServices: "خدماتنا",
        scrollText: "مرر للأسفل",
        aboutLabel: "من نحن",
        aboutTitle: "التميز الهندسي في الصلب",
        aboutSubtitle: "منشأة عالية التقنية تجمع بين التصميم والتصنيع والمعالجة السطحية وتركيب مختلف الأعمال الهيكلية الفولاذية الثقيلة.",
        aboutP1: "مصنع روافد الصلب هو منشأة متخصصة في الهندسة والتصنيع والمعالجة السطحية وتركيب مختلف الأعمال الهيكلية الفولاذية الثقيلة.",
        aboutP2: "يتكون فريقنا من مهندسين وفنيين وعمال ماهرين مؤهلين للغاية الذين ينجزون متطلبات العملاء بمعايير عالية الجودة.",
        aboutP3: "يدعم قسم الهندسة مهندسين ذوي خبرة ومجهز بأحدث البرمجيات لتنفيذ رسومات التصميم والتصنيع.",
        statISO: "معتمد ISO 9001:2015",
        statAWS: "معيار D1.1",
        statSupport: "دعم المشاريع على مدار الساعة",
        statQuality: "مراقبة الجودة 100%",
        servicesLabel: "ما نقدمه",
        servicesTitle: "خدماتنا",
        servicesSubtitle: "خدمات شاملة لتصنيع وبناء الهياكل الفولاذية للمشاريع الصناعية والتجارية والبنية التحتية.",
        service1Title: "الأعمال الفولاذية الهيكلية",
        service1Desc: "تصنيع وتركيب كامل للهياكل الفولاذية المدرفلة على الساخن والمباني ذات الهيكل الفولاذي المسبق الهندسة.",
        service2Title: "الجسور والرافعات",
        service2Desc: "تصميم وبناء الجسور الفولاذية وأنظمة الرافعات للتطبيقات الصناعية والبنية التحتية.",
        service3Title: "أعمال الألواح",
        service3Desc: "تصنيع خزانات الصوامع وغيرها من منتجات أعمال الألواح بهندسة دقيقة.",
        service4Title: "المباني ذات الهيكل المسبق",
        service4Desc: "حلول مباني معدنية مخصصة ذات هندسة مسبقة للبناء السريع.",
        service5Title: "المعالجة السطحية",
        service5Desc: "خدمات الصقل بالرمل والطلاء الكاملة التي تلبي معايير الطلاء الدولية.",
        service6Title: "أعمال البنية التحتية",
        service6Desc: "أعمال الأساسات بما في ذلك إعداد التربة والدمك وبناء الأساسات الخرسانية.",
        productsLabel: "منتجاتنا",
        productsTitle: "الحلول الفولاذية",
        productsSubtitle: "مجموعة واسعة من المنتجات الفولاذية لمختلف التطبيقات الصناعية والتجارية.",
        valuesLabel: "قيمنا",
        valuesTitle: "ما يحركنا",
        valuesSubtitle: "التزامنا بالتميز موجه بقيم أساسية تحدد كل مشروع نقوم به.",
        value1Title: "الأخلاق الإسلامية",
        value1Desc: "أعمال موجهة بالنزاهة والعدالة والصدق في جميع العلاقات.",
        value2Title: "الجودة",
        value2Desc: "عمل دؤوب يقدم أعلى جودة في كل ما نقوم به.",
        value3Title: "السلامة",
        value3Desc: "حماية قوتنا العاملة والبيئة أمر حيوي لالتزامنا.",
        value4Title: "النزاهة",
        value4Desc: "تقديم العدالة والثقة والصدق من خلال السلوك الأخلاقي.",
        value5Title: "التعاون",
        value5Desc: "العمل معاً، مشاركة المهارات لإطلاق إمكانيات فريقنا.",
        value6Title: "القيادة",
        value6Desc: "الالتزام بالتحسين المستمر مع قرارات جريئة.",
        equipmentLabel: "قدراتنا",
        equipmentTitle: "معدات متقدمة",
        equipmentSubtitle: "آلات حديثة لتصنيع الفولاذ بدقة عالية.",
        equip1Desc: "قطع ثقيل حتى ألواح 110 ملم",
        equip2Desc: "آلة القطع بالبلازما للقطع الدقيق",
        equip3Desc: "حفر مستمر في اتجاهي X و Y",
        equip4Desc: "لف المعادن بدقة عالية",
        equip5Desc: "نظام ثني هيدروليكي متزامن",
        equip6Desc: "نظام تحضير سطحي كامل",
        contactTitle: "اتصل بنا",
        contactTitle2: "تواصل معنا",
        contactText: "مستعد لبدء مشروعك القادم؟ تواصل معنا اليوم للاستشارة والحصول على عرض أسعار.",
        sendEmail: "راسلنا عبر البريد",
        callUs: "اتصل بنا",
        visitUs: "زورنا",
        footerLogo: "مصنع روافد الصلب",
        footerLogoEn: "Rawafid Alssalb Factory",
        footerCopyright: "© 2024 مصنع روافد الصلب. جميع الحقوق محفوظة.",
        footerHome: "الرئيسية",
        footerAbout: "من نحن",
        footerContact: "اتصل بنا",
        overview: "نظرة عامة",
        otherProducts: "منتجات أخرى",
        specProductLabel: "نوع المنتج",
        specCertLabel: "الشهادة",
        specSoftwareLabel: "برامج التصميم",
        specServicesLabel: "الخدمات",
        specServicesText: "التصميم، التصنيع، المعالجة السطحية، التسليم، التركيب",
        bridgesTitle: "الجسور الفولاذية",
        bridgesTitleAr: "الجسور الفولاذية",
        bridgesTagline: "حلول البنية التحتية للتطبيقات الصناعية والتجارية",
        bridgesSubtitle: "حلول البنية التحتية",
        bridgesDesc1: "متخصصون في تصميم وتصنيع وتركيب الجسور الفولاذية لمشاريع البنية التحتية.",
        bridgesDesc2: "نقدم حلول جسور عالية الجودة تلبي المعايير الدولية.",
        bridgesFeat1: "جسور الطرق والسكك الحديدية",
        bridgesFeat2: "ممرات المشاة",
        bridgesFeat3: "أنظمة الرافعات الصناعية",
        bridgesFeat4: "حسابات الأحمال والتحليل الإنشائي",
        bridgesFeat5: "معالجة سطحية كاملة",
        bridgesFeat6: "التسليم والتركيب في الموقع",
        buildingsTitle: "المباني ذات الأحمال الثقيلة",
        buildingsTitleAr: "المباني ذات الأحمال الثقيلة",
        buildingsSubtitle: "هياكل صناعية وتجارية",
        buildingsDesc: "نصنع ونركب مباني فولاذية ذات أحمال ثقيلة للمنشآت الصناعية.",
        buildingsFeat1: "هياكل فولاذية المدرفلة على الساخن",
        buildingsFeat2: "مباني معدنية ذات هندسة مسبقة",
        buildingsFeat3: "مباني صناعية متعددة الطوابق",
        buildingsFeat4: "هياكل المستودعات والمصانع",
        buildingsFeat5: "حلول تصميم مخصصة",
        buildingsFeat6: "أعمال الأساسات الكاملة",
        buildingsOverview: "الهياكل الصناعية الثقيلة",
        buildingsDesc1: "نصنع ونركب مباني فولاذية ثقيلة للمنشآت الصناعية ومصانع التصنيع والمستودعات والمجمعات التجارية التي تتطلب قدرة تحمل عالية.",
        buildingsDesc2: "نقدم حلولاً متكاملة تشمل التصميم الإنشائي وإعداد رسومات التصنيع والتصنيع الدقيق والتركيب في الموقع.",
        tanksTitle: "خزانات التخزين والصوامع",
        tanksTitleAr: "خزانات التخزين والصوامع",
        tanksSubtitle: "التخزين الصناعي",
        tanksDesc: "نصنع خزانات التخزين والصوامع للسوائل والمواد السائبة.",
        tanksFeat1: "خزانات تخزين فوق الأرض",
        tanksFeat2: "صوامع الحبوب والأسمنت",
        tanksFeat3: "أوعية الضغط",
        tanksFeat4: "خزانات تخزين الوقود",
        tanksFeat5: "خزانات تخزين المياه",
        tanksFeat6: "أعمال ألواح مخصصة",
        tanksOverview: "مرافق التخزين السائب",
        tanksDesc1: "نصنع خزانات تخزين وصوامع مصممة بدقة للسوائل ومنتجات البترول والمواد الكيميائية والحبوب والأسمنت والمواد السائبة.",
        tanksDesc2: "تم تصميم خزاناتنا وفقاً للمعايير الدولية بما في ذلك API 650 و API 620 و ASME القسم الثامن.",
        turbineTitle: "غرف التوربينات",
        turbineTitleAr: "غرف التوربينات",
        turbineSubtitle: "توليد الطاقة",
        turbineDesc: "نصمم ونصنع غرف التوربينات للتوربينات الغازية والبخارية.",
        turbineFeat1: "أساسات توربينات المولدات",
        turbineFeat2: "مباني محطات الطاقة",
        turbineFeat3: "هياكل دعم المعدات",
        turbineFeat4: "دعم مداخن العادم",
        turbineFeat5: "مباني غرف التحكم",
        turbineFeat6: "منصات المحولات",
        turbineOverview: "هياكل توليد الطاقة",
        turbineDesc1: "نصمم ونصنع غرف التوربينات وهياكل محطات الطاقة للتوربينات الغازية والبخارية. يستخدم فريقنا الهندسي برمجيات تحليل إنشائي متقدمة بما في ذلك SAP2000 و ETABS لضمان السلامة الهيكلية والمقاومة الزلزالية والامتثال لمعايير محطات الطاقة الدولية.",
        turbineDesc2: "نعمل مع شركات الطاقة الرائدة لتقديم حلول إنشائية موثوقة لمشاريع الطاقة. تضمن عملياتنا المعتمدة من ISO 9001:2015 مراقبة الجودة طوال التصميم والتصنيع والمعالجة السطحية والتركيب. تتبع جميع عمليات اللحام معايير AWS D1.1.",
        towersTitle: "أبراج الجهد العالي",
        towersTitleAr: "أبراج الجهد العالي",
        towersSubtitle: "خطوط النقل",
        towersDesc: "نصنع أبراج الجهد العالي لخطوط نقل الكهرباء.",
        towersFeat1: "أبراج نقل الكهرباء",
        towersFeat2: "هياكل المحطات الفرعية",
        towersFeat3: "أبراج محولات التوزيع",
        towersFeat4: "أبراج الاتصالات",
        towersFeat5: "هياكل دعم الهوائيات",
        towersFeat6: "أبراج التوزيع",
        hangarsTitle: "صالات للطائرات",
        hangarsTitleAr: "صالات للطائرات",
        hangarsSubtitle: "مرافق الطيران",
        hangarsDesc: "نصمم ونصنع صالات للطائرات للطيران التجاري والعسكري.",
        hangarsFeat1: "صالات صيانة الطائرات",
        hangarsFeat2: "صالات التخزين",
        hangarsFeat3: "أنظمة أبواب الصالات",
        hangarsFeat4: "هياكل إضاءة المدرج",
        hangarsFeat5: "مباني الدعم الجوي",
        hangarsFeat6: "آليات وأبواب الصالات",
        cargoTitle: "محطات الشحن",
        cargoTitleAr: "محطات الشحن",
        cargoSubtitle: "بنية التحتية اللوجستية",
        cargoDesc: "نصنع هياكل محطات الشحن للمطارات والموانئ.",
        cargoFeat1: "مباني مستودعات الشحن",
        cargoFeat2: "هياكل محطات البضائع",
        cargoFeat3: "أغطية أرصفة التحميل",
        cargoFeat4: "هياكل دعم الناقلات",
        cargoFeat5: "مرافق التخزين البارد",
        cargoFeat6: "منصات اللوجستيات",
        pebTitle: "المباني ذات الهيكل المسبق",
        pebTitleAr: "المباني ذات الهيكل المسبق",
        pebSubtitle: "المباني المعدنية المخصصة",
        pebDesc: "نقدم حلول المباني المعدنية ذات الهندسة المسبقة للبناء السريع.",
        pebFeat1: "المستودعات",
        pebFeat2: "المصانع",
        pebFeat3: "صالات العرض",
        pebFeat4: "المرافق الرياضية",
        pebFeat5: "المباني الزراعية",
        pebFeat6: "الهياكل التجارية",
        productBridges: "الجسور الفولاذية",
        productBridgesSub: "حلول البنية التحتية",
        productBuildings: "المباني ذات الأحمال الثقيلة",
        productBuildingsSub: "الهياكل الصناعية",
        productTanks: "خزانات التخزين والصوامع",
        productTanksSub: "التخزين الصناعي",
        productTurbine: "غرف التوربينات",
        productTurbineSub: "توليد الطاقة",
        productTowers: "أبراج الجهد العالي",
        productTowersSub: "خطوط النقل",
        productHangars: "صالات للطيارات",
        productHangarsSub: "مرافق الطيران",
        productCargo: "محطات الشحن",
        productCargoSub: "بنية التحتية اللوجستية",
        productPEB: "المباني ذات الهيكل المسبق",
        productPEBSub: "المباني المعدنية المخصصة",
        
        productTitle: "الجسور الفولاذية",
        productTitleAr: "Steel Bridges",
        productTagline: "حلول جسور البنية التحتية لشبكات النقل",
        productSubtitle: "بنية التحتية للنقل",
        productDesc1: "متخصص مصنع روافد الصلب في تصميم وتصنيع وتركيب الجسور الفولاذية وهياكل الرافعات لمشاريع البنية التحتية للنقل.",
        productDesc2: "نقدم حلول جسور عالية الجودة تلبي المعايير الدولية بما في ذلك مواصفات تصميم الجسور AASHTO.",
        feat1: "هياكل جسور الطرق والسكك الحديدية (امتداد حتى 100 متر)",
        feat2: "أنظمة ممرات المشاة والدراجات",
        feat3: "هياكل رافعات الرافعات الصناعية العلوية",
        feat4: "حسابات الأحمال الكاملة والتحليل الإنشائي",
        feat5: "معالجة سطحية كاملة مع الصقل بالفراغات والطلاء الواقي",
        feat6: "خدمات التسليم والتركيب في الموقع",
        specProduct: "الجسور الفولاذية ورافعات الرافعات",
        specCert: "ISO 9001:2015, AWS D1.1/D1.5",
        specSoftware: "SAP2000, ETABS, STAAD.Pro, Autodesk Advance Steel"
    }
};

let currentLang = 'en';

function setLanguage(lang) {
    currentLang = lang;
    document.documentElement.lang = lang;
    document.body.dir = lang === 'ar' ? 'rtl' : 'ltr';

    document.querySelectorAll('[data-i18n]').forEach(el => {
        const key = el.dataset.i18n;
        if (translations[lang][key]) {
            el.textContent = translations[lang][key];
        }
    });

    document.querySelectorAll('.lang-btn').forEach(btn => {
        btn.classList.toggle('active', btn.dataset.lang === lang);
    });

    localStorage.setItem('selectedLang', lang);
    
    // Dispatch custom event for product pages to listen to
    const event = new CustomEvent('languageChanged', { detail: { lang: lang } });
    window.dispatchEvent(event);
}

document.querySelectorAll('.lang-btn').forEach(btn => {
    btn.addEventListener('click', () => {
        setLanguage(btn.dataset.lang);
    });
});

const savedLang = localStorage.getItem('selectedLang');
if (savedLang) {
    setLanguage(savedLang);
}

window.addEventListener('scroll', () => {
    const navbar = document.getElementById('navbar');
    if (navbar) {
        if (window.scrollY > 50) {
            navbar.classList.add('scrolled');
        } else {
            navbar.classList.remove('scrolled');
        }
    }
});

const mobileMenu = document.querySelector('.mobile-menu');
const navLinks = document.querySelector('.nav-links');

if (mobileMenu && navLinks) {
    mobileMenu.addEventListener('click', () => {
        mobileMenu.classList.toggle('active');
        navLinks.classList.toggle('active');
    });

    document.querySelectorAll('.nav-links a').forEach(link => {
        link.addEventListener('click', () => {
            mobileMenu.classList.remove('active');
            navLinks.classList.remove('active');
        });
    });
}

// Contact form removed - using direct email/phone links instead
